# Generated by Django 4.2.11 on 2024-05-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
