# Generated by Django 4.2.13 on 2024-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
